(function(q){var e=q,h=document,D=e.location;if(!e.TJ58){e.TJ58=!0;null==e.String.prototype.trim&&(e.String.prototype.trim=function(){return this.replace(/^\s\s*/,"").replace(/\s\s*$/,"")});e.TJ58Obj={};var f={curURL:D.href,referrer:h.referrer,protocol:D.protocol,window_size:h.documentElement.clientWidth+"x"+h.documentElement.clientHeight,screen_size:e.screen.width+","+e.screen.height,domain:function(){var a=D.host.toLowerCase(),c=/.*?([^\.]+\.(com|org|net|biz|edu|cc)(\.[^\.]+)?)/;return c.test(a)?
"."+a.replace(c,"$1"):""}(),navigation_type:function(){var a="-1";try{a=e.performance.navigation.type}catch(c){return"-1"}return a}(),setCookie:function(){if(!h.cookie)return!1;var a=new Date;2<arguments.length?a.setTime(a.getTime()+864E5*arguments[2]):a.setTime(a.getTime()+18E5);2<=arguments.length&&(h.cookie=arguments[0]+"="+escape(arguments[1])+"; expires="+a.toGMTString()+"; domain="+f.domain+"; path=/")},getCookie:function(a){if(!h.cookie)return"";var c;return(c=h.cookie.match(RegExp("(^| )"+
a+"=([^;]*)(;|$)")))?unescape(c[2]):""},ajaxsend:function(a){(new Image).src=a},getGTID:function(a,c,b){function e(a,c,b){a=(""+a).length<c?(Array(c+1).join("0")+a).slice(-c):""+a;return-1==b?a:a.substring(0,b)+"-"+a.substring(b)}var r={home:"1",index:"2",list:"3",detail:"4",post:"5",special:"6"};a=r[a]?parseInt(r[a]).toString(16):0;c=c.split(",");c=c[c.length-1];c=parseInt(c)?parseInt(c).toString(16):0;b=b.split(",");b=b[b.length-1];b=parseInt(b)?parseInt(b).toString(16):0;r=(13).toString(16);return"llpccccc-tttt-txxx-xxxx-xxxxxxxxxxxx".replace(/x/g,
function(a){return(16*Math.random()|0).toString(16)}).replace(/ccccc/,e(c,5,-1)).replace(/tttt-t/,e(b,5,4)).replace(/p/,e(a,1,-1)).replace(/ll/,e(r,2,-1))},setLocalStorage:function(a,c){try{e.localStorage&&e.localStorage.setItem(a,c)}catch(b){}},getLocalStorage:function(a){try{return e.localStorage?e.localStorage.getItem(a):""}catch(c){return""}},getUUID:function(a){var c="xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var c=16*e.Math.random()|0;return("x"==a?c:c&3|8).toString(16)}),
c=this.getCookie(a)||this.getLocalStorage(a)||c;this.setCookie(a,c,365);this.setLocalStorage(a,c);return c},getRandom:function(){return e.Math.random()},bindElem:function(a,c,b){if(e.$&&"string"==typeof a&&"string"==typeof c&&"function"==typeof b)if("function"===typeof $(h).on)$(h).on(c,a,b);else"function"===typeof $(h).delegate?$(h).delegate(a,c,b):"function"===typeof $(a).bind&&$(a).bind(c,b)},loadScript:function(a,c){try{var b=h.createElement("script");b.type="text/javascript";b.readyState?b.onreadystatechange=
function(){if("loaded"==b.readyState||"complete"==b.readyState)b.onreadystatechange=null,c&&c()}:b.onload=function(){c&&c()};b.src=a;h.body.appendChild(b)}catch(e){}}},d={config:{trackLog:{server:"tracklog.58.com/m/empty.js.gif",allParams:"site_name tag referrer post_count _trackParams userid smsc window_size _ga_utma trackURL rand_id".split(" "),uniqParams:["tag","rand_id"]},loadMorePageLog:{server:"tracklog.58.com/m/empty.js.gif",allParams:"site_name tag referrer post_count _trackParams userid smsc window_size _ga_utma trackURL EventTag rand_id".split(" "),
uniqParams:["tag","EventTag","rand_id"]},listShowLog:{server:"tracklog.58.com/Mv1/listshow/empty.js.gif",allParams:"tag bangbangid referrer site_name info_data trackURL rand_id".split(" "),uniqParams:["tag","info_data","rand_id"]},listClickLog:{server:"tracklog.58.com/Mv1/listclick/empty.js.gif",allParams:"tag bangbangid referrer site_name info_data trackURL ClickID rand_id".split(" "),uniqParams:["tag","info_data","rand_id"]},clickLog:{server:"tracklog.58.com/m/click/empty.js.gif",allParams:"site_name tag from trackURL ClickID bangbangid referrer rand".split(" "),
uniqParams:["tag","from","rand"]},diaTrackLog:{server:"dialog.58.com/transfer",allParams:"DIATag referrer post_count _trackParams userid smsc window_size _ga_utma trackURL rand_id".split(" "),uniqParams:["DIATag","rand_id"]},diaClickLog:{server:"dialog.58.com/transfer",allParams:"DIATag from trackURL ClickID bangbangid referrer rand".split(" "),uniqParams:["DIATag","from","rand"]},diaShowLog:{server:"dialog.58.com/transfer",allParams:"DIATag trackURL ClickID bangbangid referrer rand".split(" "),uniqParams:["DIATag",
"rand"]},gdtTrackLog:{server:"gdt.cm.58.com/gdtcm",allParams:["city","cate","plat"],uniqParams:["city","plat"]},gdtTrackLog2:{server:"gdtcm.58.com/gdtcm",allParams:["city","cate","plat"],uniqParams:["city","plat"]}},filterList:function(a){var c=".58.com.cn portal.58.com faw-vw-dasweltauto.58.com 5858.com lieche.58.com dict.58.com/xiaoqu about.58.com m.58.com/city.html lieche.m.58.com".split(" "),b;for(b in c)if(-1!==a.indexOf(c[b]))return"YES";return"NO"},isRealIndexPage:function(a){var c=[/^http:\/\/m.58.com\/[^\/]*\/job.shtml/,
/^http:\/\/m.58.com\/[^\/]*\/house.shtml/,/^http:\/\/m.58.com\/[^\/]*\/car.shtml/,/^http:\/\/m.58.com\/[^\/]*\/sale.shtml/,/^http:\/\/m.58.com\/[^\/]*\/jianzhi.shtml/,/^http:\/\/m.58.com\/[^\/]*\/pets.shtml/,/^http:\/\/m.58.com\/[^\/]*\/shenghuo.shtml/,/^http:\/\/m.58.com\/[^\/]*\/bendishenghuo.shtml/,/^http:\/\/m.58.com\/[^\/]*\/bendishangwu.shtml/,/^http:\/\/m.58.com\/[^\/]*\/huangye.shtml/],b;for(b in c)if(a.match(c[b]))return"YES";return"NO"},getBaseInfo:function(){var a=q.site_name||"M58",c=
q.encodeURIComponent(f.referrer),b=f.curURL,E=f.getUUID("58tj_uuid"),r=f.getCookie("bangbangid"),n=f.window_size,G=f.navigation_type,m=f.screen_size,g=q.____json4fe?q.____json4fe:{},l=g._trackPagetype||"",k=g._trackURL||"",d=g._trackParams||[],h=g.GA_pageview||"",D=g.infoid||"",R=g.userid||"",S=g.smsc||"",g=g.sid||"",v=q._trackURL||k||"NA",s={};try{s="NA"===v?{}:eval("("+v+")")}catch(Y){s={}}var l=s.pagetype||l||q.page_type||"NA",k=s.post_count||q.post_count||-1,h=s.Ga_pageview||h||"",y=s.cate||"",
T=""===y?"":y.split(",")[0],U=""===y&&-1===y.indexOf(",")?"":y.split(",")[1],H=s.area||"",P=""===H?"":H.split(",")[0],V=s.actiontype||"",Q=f.getGTID(l,y,H),s=s.ROI||"",W=f.getCookie("br58")||"",M=f.getCookie("myLat")||"",p=f.getCookie("myLon")||"",M=M+"_"+p,p=e._trackParams||d||[],z=[],d="";if(p instanceof Array){for(var d=0,N=p.length;d<N;d++)p[d]&&p[d].I&&p[d].V&&"string"===typeof p[d].V&&z.push(p[d].I+":"+p[d].V.replace(/\|/g,"*"));d=encodeURIComponent(z.join("@@"))}var z=(p=f.curURL.match(/[\?&]iuType=[a-z]*_[0-9]*/))?
p[0].split("=")[1].split("_"):["",""],p=z[0],z=z[1],N=f.getCookie("als"),O=f.getCookie("utm_source"),X=f.getCookie("utm_campaign"),I=f.getCookie("spm"),A,F,J;""!=f.getCookie("new_session")?(A=f.getCookie("init_refer"),F="0"):(A=q.encodeURIComponent(f.referrer),F="1");J=""!=f.getCookie("new_uv")?parseInt(f.getCookie("new_uv"))+("0"==F?0:1):1;f.setCookie("new_session",F);f.setCookie("new_uv",J,365);var t=!1,u=f.referrer.split("/")[2]||"",B=f.curURL.split("/")[2]||"",w=this.getValByUrl(f.curURL,"utm_source"),
x=this.getValByUrl(f.curURL,"spm"),K=f.getCookie("qz_gdt"),C=this.getValByUrl(f.curURL,"qz_gdt");"NA"==C||""==C?(C=!1,"NA"==x||""==x?u&&-1===u.indexOf(".58.com")&&-1===u.indexOf(".5858.com")&&-1===u.indexOf(".58cdn.com.cn")&&(C=!0):("NA"==x?"":x)!=I&&(C=!0),C&&(K="")):K=C;f.setCookie("qz_gdt",K);if("NA"!=this.getValByUrl(f.curURL,"-15")||B&&-1!=B.indexOf("luna.58.com"))t="NA";f.referrer||"NA"==w&&"NA"==x?f.referrer||"NA"!=w||"NA"!=x||"1"!==F?u&&-1===u.indexOf(".58.com")&&-1===u.indexOf(".5858.com")&&
-1===u.indexOf(".58cdn.com.cn")&&(A=q.encodeURIComponent(f.referrer),t="NA"==t?!1:!0):(A="",t="NA"==t?!1:!0):(A="",t="NA"==t?!1:!0);t&&"NA"!=t&&(O="NA"===w?"":w,I="NA"===x?"":x);f.setCookie("utm_source",O);f.setCookie("spm",I);f.setCookie("init_refer",A);var t="1.1.1.1.1."+J,u=f.getCookie("bbsession_uid"),B=[],w=v.indexOf("{"),G={GTID:Q,infoid:D,infotype:p,usertype:z,als:N,utm_source:O,utm_campaign:X,spm:I,qz_gdt:K,br58:W,coords:M,new_session:F,init_refer:A,new_uv:J,UUID:E,bangbangid:u,navtype:G,
sc:m,sid:g},L;for(L in G)G.hasOwnProperty(L)&&B.push("'"+L+"':'"+G[L]+"'");B.join(",");v="NA"!==v&&-1!==w?v.substring(0,w+1)+B+","+v.substring(w+1):"{"+B+"}";return{site_name:a,referrer:c,UUID:E,bangbangid:r,pagetype:l,post_count:k,cate:y,cate1:T,cate2:U,area:H,area1:P,city:P,actiontype:V,GTID:Q,ClickID:1,ROI:s,curURL:b,_trackParams:d,userid:R,smsc:S,window_size:n,trackURL:v,Ga_pageview:h,_ga_utma:t,ClickIDPlus:function(){this.ClickID+=1},curIndex:0,curPageNum:1}},getValByUrl:function(a,c){var b;
b=a.match(RegExp("[&?]"+c+"=([^&|^#]*)"));return b instanceof Array?b[1]:"NA"},sendLog:function(a,c){var b=this.baseInfo,e=this.config[a];if(a&&e&&c&&"object"===typeof c){for(var r=[],n=e.allParams,d=0,m=n.length;d<m;d++)r.push(n[d]+"="+(c[n[d]]||b[n[d]]||""));f.ajaxsend(f.protocol+"//"+e.server+"?"+r.join("&"))}},trackLog:function(){var a=this.baseInfo;this.sendLog("trackLog",{tag:"pvstatall",rand_id:f.getRandom()});if("list"===a.pagetype||"detail"===a.pagetype)"https:"==f.protocol?this.sendLog("gdtTrackLog2",
{city:a.area,plat:"M"}):this.sendLog("gdtTrackLog",{city:a.area,plat:"M"})},clickLog:function(a){var c="",c=null!=a&&"from="===a.substring(0,5)?a.replace("from=",""):"default&"+a;this.sendLog("clickLog",{tag:"pvsiters",from:c,rand:f.getRandom()});setTimeout("GCIDPlus()",300)},listClickLog:function(){var a=this,c=this.baseInfo;if(e.$&&"list"===c.pagetype&&"NA"!=c.trackURL){var b=function(b){if(b){var e=$(b).parents("[logr]");b=e.attr("logr");var d="",d="";if(b){var E=[];b=b.split("_");E.push(b[0],
b[1],b[2],b[3]);if(4<b.length)var g=b[b.length-1],g=g.replace("ses^","ses:"),d=d+g;g=e.attr("pos");d+=g?"@pos:"+g:"";if("9224"==c.cate1||"13941"==c.cate1)g=e.attr("_pos"),e=e.attr("sortid"),d=d+(g?"@npos:"+g:"")+(e?"@sortid:"+e:"");""!=d&&(0===d.indexOf("@")&&(d=d.substring(1)),E.push(d));d=E.join("_");"NO"==a.filterList(c.curURL)&&-1!=c.curURL.indexOf(".58.com")&&(e=$(this).attr("href")||"#",-1!=e.indexOf("javascript:")||"#"==e.substring(0,1)||"NO"!=a.filterList(e)||"/"!=e.substring(0,1)&&-1==e.indexOf(".58.com")||
e.match(/[\?&]iuType=/)||$(this).attr("href",e.trim()+(-1==e.indexOf("?")?"?":"&")+"iuType="+b[0]+"_"+b[1]));a.sendLog("listClickLog",{tag:"mlistclick",info_data:d,rand_id:f.getRandom()});setTimeout("GCIDPlus()",300)}}},d=$("[tongji_label=listclick]");d&&0<d.length?f.bindElem("[logr] [tongji_label=listclick]","click",function(){b($(this))}):f.bindElem("li[logr] a","click",function(){var a=$(this).attr("class");"function"==typeof $(this).parents&&"diyu_sale"!=a&&"company_job"!=a&&b($(this))})}},oldListClickLog:function(a){this.sendLog("oldListClickLog",
{tag:"mlistclick",bi_val_pos:a.replace("&bi_val_pos=",""),rand:f.getRandom()});setTimeout("GCIDPlus()",300)},listShowLog:function(){var a=this.baseInfo,c=a.cate1,b=[];if(e.$&&"list"===a.pagetype&&"function"==typeof $("li[logr]").attr){for(var d=$("li[logr]"),r=d.length,n=a.curPageNum,h=a.curIndex;h<r;h++){var m=$(d[h]),g=m.attr("logr"),l=m.attr("pagenum");if(1===n||n===l)if(g){var g=[],k=m.attr("logr").split("_"),l="";g.push(k[0],k[1],k[2],k[3]);4<k.length&&(k=k[k.length-1],k=k.replace("ses^","ses:"),
l+=k);k=m.attr("pos");l+=k?"@pos:"+k:"";if("9224"===c||"13941"===c)k=m.attr("_pos"),m=m.attr("sortid"),l+=k?"@npos:"+k:"",l+=m?"@sortid:"+m:"";""!=l&&(0===l.indexOf("@")&&(l=l.substring(1)),g.push(l));b.push(g.join("_"))}else g=m.attr("post_type"),l=m.attr("enum_user"),k=m.attr("uid"),m=m.attr("infoid"),g=g+"_"+l+"_"+k+"_"+m,m&&"function"===typeof $("[infoid]").index&&(k=$("[infoid]").index($(this))+1,g+="_@pos:"+k),b.push(g);else if(!(n>l))break}a.curIndex=h;this.sendLog("listShowLog",{tag:"mlistshow",
info_data:b.join(","),rand_id:f.getRandom()})}},bindTongji_tag:function(){if(e.$){var a=this;f.bindElem("[tongji_tag]","click",function(){var c=$(this).attr("tongji_tag"),b=$(this).text().trim();a.clickLog("from="+c+"&text="+encodeURIComponent(b)+"&tongji_type=tongji_tag")})}},bindTongji_id:function(){if(e.$){var a=this;f.bindElem("[tongji_id]","click",function(c){var b=c.srcElement?c.srcElement:c.target;"A"==b.tagName.toUpperCase()&&(c=$(b).attr("href")||"#",b=$(b).text(),-1==c.indexOf("javascript:")&&
"#"!=c.substring(0,1)&&a.clickLog("from="+$(this).attr("tongji_id")+"&text="+encodeURIComponent(b)+"&to="+encodeURIComponent(c)+"&tongji_type=tongji_id"))})}},diaShowLog:function(a){},loadMorePageLog:function(a){var c=this.baseInfo;if(a&&-1!=a.indexOf("pagenum=")){var b=a.split("=",-1)[1];c.trackURL=c.trackURL.replace(/'pagenum':[^,}&]*/,"'pagenum':'"+b+"'");c.curPageNum=b}this.sendLog("loadMorePageLog",{tag:"pvstatall",EventTag:"loadMorePage&"+a,rand_id:f.getRandom()});this.listShowLog()},bindAlsTag:function(){if(!f.getCookie("als")&&
e.$&&"function"===typeof $("body").one)$("body").one("mouseover",function(){f.setCookie("als","0",365)});f.getCookie("isSpider")&&f.setCookie("isSpider","",0)},bindHomeHeatMap:function(){var a=this.baseInfo;if(e.$&&"home"===a.pagetype&&"m_zhuzhan"===a.actiontype)for(var c=$("[tongji_tag]"),b=0;b<c.length;b++){var d=c[b],f=$(d).attr("href")||"#",n=$(d).attr("tongji_tag")||"NA";-1==f.indexOf("javascript:")&&"#"!=f.substring(0,1)&&(f=f.match(/[\?&]58hm=[^&]*/)?f.replace(/58hm=[^&]*/,"58hm="+n):f.trim()+
(-1==f.indexOf("?")?"?":"&")+"58hm="+n,f=f.match(/[\?&]58cid=[^&]*/)?f.replace(/58cid=[^&]*/,"58cid="+a.area1):f.trim()+(-1==f.indexOf("?")?"?":"&")+"58cid="+a.area1,$(d).attr("href",f))}},bindIndexHeatMap:function(){var a=this.baseInfo;if(e.$&&"index"===a.pagetype&&"m_zhuzhan"===a.actiontype&&"YES"==this.isRealIndexPage(a.curURL))for(var c=$("[tongji_tag]"),b=0;b<c.length;b++){var f=c[b],d=$(f).attr("href")||"#",n=$(f).attr("tongji_tag")||"NA";-1==d.indexOf("javascript:")&&"#"!=d.substring(0,1)&&
(d=d.match(/[\?&]58ihm=[^&]*/)?d.replace(/58ihm=[^&]*/,"58ihm="+n):d.trim()+(-1==d.indexOf("?")?"?":"&")+"58ihm="+n,d=d.match(/[\?&]58cid=[^&]*/)?d.replace(/58cid=[^&]*/,"58cid="+a.area1):d.trim()+(-1==d.indexOf("?")?"?":"&")+"58cid="+a.area1,$(f).attr("href",d))}},bindAddGTIDtoURL:function(){var a=this,c=this.baseInfo;e.$&&f.bindElem("a","click",function(){if("NO"==a.filterList(c.curURL)&&-1!=c.curURL.indexOf(".58.com")){var b=$(this).attr("href")||"#";if(-1==b.indexOf("javascript:")&&"#"!=b.substring(0,
1)&&"NO"==a.filterList(b)&&("/"==b.substring(0,1)||-1!=b.indexOf(".58.com")))if(b.match(/[\?&]ClickID=\d*/))$(this).attr("href",b.replace(/ClickID=\d*/,"ClickID="+c.ClickID));else{var e=b.indexOf("?");-1!=e&&-1!=b.substring(e).indexOf("statmark=t")&&-1!=b.substring(e).indexOf("#")?(e=b.indexOf("statmark=t"),$(this).attr("href",b.substring(0,e+10)+"&PGTID="+c.GTID+"&ClickID="+c.ClickID+b.substring(e+10))):$(this).attr("href",b.trim()+(-1==e?"?":"&")+"PGTID="+c.GTID+"&ClickID="+c.ClickID)}}})},insertMiGuan:function(){try{var a=
"default";switch(this.baseInfo.cate1){case "9224":case "9225":case "13941":case "13952":a="yewu";break;case "1":a="ershoufang";break;case "5":a="shouji";break;case "832":a="dog";break;case "4":a="ershouche";break;default:a="shenghuo"}var c=Math.ceil(1E14*Math.random()),b=document.getElementsByTagName("body")[0],e=document.createElement("div");e.id="addInfo";e.style.display="none";var d=document.createElement("a");d.href=f.protocol+"//tracklog.58.com/detail/m/"+a+"/"+c+"x.shtml";d.text="\u63a8\u8350\u4fe1\u606f";
e.appendChild(d);b.appendChild(e)}catch(n){}},bindUndefinedClickLog:function(){if(e.limited_show){var a=limited_show.replace(/\[/g,"").replace(/\]/g,"").trim().split(","),c;for(c in a)a[c].trim()&&this.clickLog(a[c].trim())}if(e._statisArr)for(a=e._statisArr;a instanceof Array&&0<a.length;)c=a.shift(),c instanceof Array?this.clickLog("from="+c[0]+"&sumval="+c[1]):this.clickLog(c)},performanceLog:function(){var a=this.baseInfo,c=!1,b="home index list special post detail tongzhen".split(" "),d;for(d in b)if(a.pagetype==
b[d]){c=!0;break}if(c&&e.performance&&e.performance.timing){var f=e.onload;q.onload=function(){function a(c,b,e){return"number"===typeof c&&"number"===typeof b?(c-=b,c=Math.floor(0>c?-1:c),-1==c&&e?e:c):-1}function c(b){var d=e.performance.timing,f={loadPage:0==d.navigationStart?a(d.loadEventEnd,d.fetchStart,b):a(d.loadEventEnd,d.navigationStart,b),domReady:a(d.domComplete,d.responseEnd,b),redirect:a(d.redirectEnd,d.redirectStart,b),lookupDomain:a(d.domainLookupEnd,d.domainLookupStart,b),ttfb:0==
d.navigationStart?a(d.responseStart,d.fetchStart,b):a(d.responseStart,d.navigationStart,b),request:a(d.responseEnd,d.requestStart,b),loadEvent:a(d.loadEventEnd,d.loadEventStart,b),appcache:a(d.domainLookupStart,d.fetchStart,b),unloadEvent:a(d.unloadEventEnd,d.unloadEventStart,b),connect:a(d.connectEnd,d.connectStart,b),DOMContentLoaded:a(d.domContentLoadedEventEnd,d.fetchStart,b)};e.chrome&&e.chrome.loadTimes()&&(f.firstPaint=a(1E3*e.chrome.loadTimes().firstPaintTime,d.fetchStart,b));b=[];for(var h in f)f.hasOwnProperty(h)&&
b.push("'"+h+"':'"+f[h]+"'");b.join(",");f=getTrackURL();h=f.indexOf("{");f="NA"!==f&&-1!==h?f.substring(0,h+1)+b+","+f.substring(h+1):"{"+b+"}";b=[];b.push("site_name=58");b.push("tag=performance");b.push("referrer="+q.encodeURIComponent(document.referrer));b.push("trackURL="+f);b.push("rand_id="+e.Math.random());f=D.protocol+"//tracklog.58.com/Mv1/performance/empty.js.gif?"+b.join("&");(new Image).src=f;e.TJ58Obj.send=!0;clearInterval(e.TJ58Obj.PFORMINTERVAL)}f&&"function"==typeof e.onload&&f();
if("undefined"==typeof e.TJ58Obj.send){e.TJ58Obj.PFORMCOUNT=-1;e.TJ58Obj.send=!1;var b=e.unload;e.unload=function(){b&&"function"==typeof e.unload&&b();e.TJ58Obj.send||c("close_"+Math.floor(e.performance.now()))};e.TJ58Obj.PFORMINTERVAL=setInterval(function(){e.TJ58Obj.PFORMCOUNT++;6<e.TJ58Obj.PFORMCOUNT&&clearInterval(e.TJ58Obj.PFORMINTERVAL);try{0<e.performance.timing.loadEventEnd?c():6<=e.TJ58Obj.PFORMCOUNT&&c("TIMEOUT_"+Math.floor(e.performance.now()))}catch(a){clearInterval(e.TJ58Obj.PFORMINTERVAL)}},
500)}}}},DMloadByTag:function(){try{var a=this.getValByUrl(f.curURL,"dm-statistic-detect"),c=f.getCookie("dm-statistic-detect");if(a=("NA"==a?"":a)||c||"")switch(e.TJ58ecdata={},e.TJ58ecdata.platform="58M",a){case "2":f.loadScript("http://stat.58corp.com/static/js/referrer_alert.js");break;case "3":f.loadScript("http://stat.58corp.com/static/js/referrer_visual.js")}}catch(b){}}};d.baseInfo=d.getBaseInfo();d.trackLog();d.listShowLog();d.listClickLog();d.bindAlsTag();d.bindTongji_tag();d.bindTongji_id();
d.bindHomeHeatMap();d.bindIndexHeatMap();d.bindAddGTIDtoURL();d.bindUndefinedClickLog();d.insertMiGuan();e.clickLog=function(a){d.clickLog(a)};e.showLog=function(a){};e.loadMorePage=function(a){d.loadMorePageLog(a)};e.ajaxlog_mlistshow=function(){d.listShowLog()};e.GCIDPlus=function(){d.baseInfo.ClickIDPlus()};e.listClickLog=function(a){};e.reTrackLog=function(){d.baseInfo=d.getBaseInfo();d.trackLog();d.listShowLog()};e.getGTID=function(){return d.baseInfo.GTID};e.getTrackURL=function(){return d.baseInfo.trackURL};
d.performanceLog();e._gaq=e._gaq||[];d.DMloadByTag()}})(window);
